-- migrate:up
-- (seu SQL “para frente” aqui)
-- exemplos:
-- CREATE TABLE IF NOT EXISTS profiles (...);
-- CREATE TABLE IF NOT EXISTS interests (...);
-- ALTER TABLE ...;

-- migrate:down
-- (seu SQL de rollback)
-- DROP TABLE IF EXISTS interests;
-- DROP TABLE IF EXISTS profiles;
