app = "backend-jdzi8w"
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false     # <- NÃO autostop
  min_machines_running = 1       # <- mantém 1 VM viva
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    name = "healthz"
    type = "http"
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "15s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
