app = "backend-jdzi8w"
primary_region = "gru"

# Opcional: só se você precisar de buildpacks em vez de Dockerfile
# [build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1
  processes = ["app"]

  # Handlers padrão (TLS na 443 e HTTP na 80)
  [[http_service.handlers]]
    handler = "tls"

  [[http_service.handlers]]
    handler = "http"

  # Health check HTTP -> /healthz
  [[http_service.checks]]
    type = "http"
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/healthz"
    grace_period = "10s"
