app = "backend-jdzi8w"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false   # <— manter ligado
  min_machines_running = 1     # <— ao menos 1 VM ativa
  processes = ["app"]

  [[http_service.checks]]
    type = "http"
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/healthz"

[checks]
  [checks.status]
    type = "http"          # <- Faltava isso
    port = 8080
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
