app = "backend-jdzi8w"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

[checks]
  [checks.status]
    type = "http"          # <- Faltava isso
    port = 8080
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
