name: Deploy to Staging

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Migrate DB and Deploy (staging)
    runs-on: ubuntu-latest

    # <— ESSENCIAL: conecta o job ao environment 'staging'
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Install dbmate
        run: |
          curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
          sudo chmod +x /usr/local/bin/dbmate
          dbmate --version

      - name: Sanity check DATABASE_URL secret
        run: |
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "DATABASE_URL secret missing" && exit 1
          fi
          echo "DATABASE_URL secret is present."

      - name: Run migrations on STAGING
        run: dbmate --migrations-dir=db/migrations --no-dump-schema --url "${{ secrets.DATABASE_URL }}" up
