name: Deploy to Staging
on: { workflow_dispatch: {} }

jobs:
  deploy:
    name: Migrate DB and Deploy (staging)
    runs-on: ubuntu-latest
    environment: { name: staging }

    steps:
      - uses: actions/checkout@v4

      # Diagnóstico em "compile-time" (sem usar env) — falha se o secret não existe no contexto
      - name: Check if secrets.DATABASE_URL exists (compile-time)
        run: |
          echo "Has JWT_SECRET? -> ${{ secrets.JWT_SECRET != '' }}"
          echo "Has DATABASE_URL? -> ${{ secrets.DATABASE_URL != '' }}"
          if [ "${{ secrets.DATABASE_URL }}" = "" ]; then
            echo "secrets.DATABASE_URL NOT FOUND in this workflow context"; exit 1
          fi
          echo "secrets.DATABASE_URL is visible to this workflow."

      - name: Install dbmate
        run: |
          curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
          sudo chmod +x /usr/local/bin/dbmate
          dbmate --version

      - name: Sanity check (runtime env)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "DATABASE_URL length: $(echo -n "$DATABASE_URL" | wc -c)"
          [ -z "$DATABASE_URL" ] && echo "DATABASE_URL empty at runtime" && exit 1

      - name: Run migrations on STAGING
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: dbmate up
