name: Deploy to Staging

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Migrate DB and Deploy (staging)
    runs-on: ubuntu-latest

    # 🔥 liga o job ao environment "staging"
    environment: staging

    # 🔥 injeta os secrets como variáveis de ambiente do job
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Sanity check (não vaza valor)
        run: |
          if [ -z "${DATABASE_URL}" ]; then
            echo "DATABASE_URL secret missing" && exit 1
          fi
          echo "DATABASE_URL is set (len=$(echo -n "$DATABASE_URL" | wc -c))"

      - name: Install dbmate
        run: |
          curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
          sudo chmod +x /usr/local/bin/dbmate
          dbmate --version

      - name: Run migrations on STAGING
        run: dbmate up
