name: Deploy Staging

on:
  push:
    branches: [ main ]

jobs:
  migrate-and-deploy:
    runs-on: ubuntu-latest
    environment: { name: staging }
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dbmate + psql
        run: |
          curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
          sudo chmod +x /usr/local/bin/dbmate
          sudo apt-get update -y && sudo apt-get install -y postgresql-client

      - name: Sanity (DATABASE_URL)
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
        run: |
          [ -z "$DATABASE_URL" ] && echo "DATABASE_URL vazio" && exit 1
          if echo "$DATABASE_URL" | grep -qiE '@(localhost|127\.0\.0\.1)'; then
            echo "Recusando localhost em CI"; exit 1
          fi

      - name: Smoke test psql
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
        run: psql "$DATABASE_URL" -tAc "select 1;"

      - name: Run migrations (dbmate up)
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
        run: dbmate up

      - name: Deploy to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="$HOME/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          flyctl deploy --remote-only --config ./fly.toml --app backend-jdzi8w
