      - name: Debug env visibility (TEMP)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # imprime “set” se a var veio do secrets (sem mostrar o valor)
          if [ -n "${DATABASE_URL+x}" ]; then echo "DATABASE_URL is set"; else echo "DATABASE_URL is NOT set"; fi
